#ifndef SERVER_DATAREPLAY_GLOBAL_H
#define SERVER_DATAREPLAY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERVER_DATAREPLAY_LIBRARY)
#  define SERVER_DATAREPLAY_EXPORT Q_DECL_EXPORT
#else
#  define SERVER_DATAREPLAY_EXPORT Q_DECL_IMPORT
#endif

#endif // SERVER_DATAREPLAY_GLOBAL_H
